### ISSUE TITLE
Security token issues

### ISSUE THREAD

**Issue by stephenmueller** [internetofhomethings/AWS-ESP8266-API#1]
Seeing the following error when I run this example, can't quite figure out what the issues is. I'm definitely sending the correct key and password.

ERROR: Invalid request: The security token included in the request is invalid.

**Comment by internetofhomethings** [comment]
I hope you got satisfactory resolution as I see you have closed the issue.
Regards,
Dave

```
  From: stephenmueller <notifications@github.com>
```

 To: internetofhomethings/AWS-ESP8266-API AWS-ESP8266-API@noreply.github.com 
 Sent: Sunday, January 31, 2016 5:32 PM
 Subject: Re: [AWS-ESP8266-API] Security token issues (#1)

Closed #1.—
